name: Qoder Mention

permissions:
  issues: write
  pull-requests: write
  contents: read
  id-token: write

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned]
  pull_request_review:
    types: [submitted]

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub event context
        env:
          GITHUB_EVENT_CONTEXT: ${{ toJson(github.event) }}
        run: echo "$GITHUB_EVENT_CONTEXT"

  qoder-mention:
    needs: debug
    if: |
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@qoder')) ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@qoder')) ||
      (github.event_name == 'pull_request_review' && contains(github.event.review.body, '@qoder')) ||
      (github.event_name == 'issues' && contains(github.event.issue.body, '@qoder'))
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Qoder Action
        uses: ./ # Uses the local action
        with:
          scene: mention
          dashscope_api_key: ${{ secrets.DASHSCOPE_API_KEY }}